# Generated by Django 6.0.6 on 2026-06-26 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="URL 标识"
                    ),
                ),
                (
                    "summary",
                    models.CharField(blank=True, max_length=240, verbose_name="摘要"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "入门"),
                            ("medium", "进阶"),
                            ("hard", "挑战"),
                        ],
                        default="easy",
                        max_length=16,
                        verbose_name="难度",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="Python", max_length=48, verbose_name="分类"
                    ),
                ),
                (
                    "statement",
                    models.TextField(db_column="description", verbose_name="题目描述"),
                ),
                (
                    "input_description",
                    models.TextField(blank=True, verbose_name="输入说明"),
                ),
                (
                    "output_description",
                    models.TextField(blank=True, verbose_name="输出说明"),
                ),
                ("constraints", models.TextField(blank=True, verbose_name="数据范围")),
                ("starter_code", models.TextField(blank=True, verbose_name="初始代码")),
                (
                    "time_limit_seconds",
                    models.FloatField(default=1.5, verbose_name="单测超时秒"),
                ),
                (
                    "memory_limit_mb",
                    models.PositiveIntegerField(
                        default=128, verbose_name="内存限制 MB"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="发布"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Python 判题题目",
                "verbose_name_plural": "Python 判题题目",
                "db_table": "python_judge_pythonjudgeproblem",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="JudgeTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_column="name",
                        max_length=80,
                        verbose_name="测试点名称",
                    ),
                ),
                ("stdin", models.TextField(verbose_name="输入")),
                (
                    "expected_stdout",
                    models.TextField(
                        db_column="expected_output", verbose_name="期望输出"
                    ),
                ),
                ("explanation", models.TextField(blank=True, verbose_name="说明")),
                (
                    "is_sample",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="样例"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="启用"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="python_judge.judgeproblem",
                        verbose_name="题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "Python 判题测试点",
                "verbose_name_plural": "Python 判题测试点",
                "db_table": "python_judge_pythonjudgetestcase",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="JudgeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(verbose_name="提交代码")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "通过"),
                            ("wrong_answer", "答案错误"),
                            ("runtime_error", "运行错误"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="结果",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(default=0, verbose_name="得分"),
                ),
                (
                    "passed_count",
                    models.PositiveIntegerField(default=0, verbose_name="通过数"),
                ),
                (
                    "total_count",
                    models.PositiveIntegerField(default=0, verbose_name="总数"),
                ),
                ("case_results", models.TextField(blank=True, verbose_name="判题详情")),
                ("stdout", models.TextField(blank=True, verbose_name="标准输出")),
                ("stderr", models.TextField(blank=True, verbose_name="标准错误")),
                (
                    "runtime_ms",
                    models.PositiveIntegerField(
                        db_column="execution_time_ms",
                        default=0,
                        verbose_name="运行耗时毫秒",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="python_judge.judgeproblem",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Python 判题提交",
                "verbose_name_plural": "Python 判题提交",
                "db_table": "python_judge_pythonjudgesubmission",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "problem", "-created_at"],
                        name="python_judg_user_id_7f4576_idx",
                    ),
                    models.Index(
                        fields=["problem", "status"],
                        name="python_judg_problem_a672ef_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProblemState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "未开始"),
                            ("attempted", "已尝试"),
                            ("accepted", "已通过"),
                        ],
                        db_index=True,
                        default="todo",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "marked",
                    models.BooleanField(
                        db_column="is_marked",
                        db_index=True,
                        default=False,
                        verbose_name="标记",
                    ),
                ),
                ("current_code", models.TextField(blank=True, verbose_name="当前答案")),
                (
                    "custom_input",
                    models.TextField(
                        blank=True, db_column="note", verbose_name="自定义输入"
                    ),
                ),
                (
                    "last_verdict",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="最近结果"
                    ),
                ),
                (
                    "last_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="最近得分"
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近运行"
                    ),
                ),
                (
                    "last_submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近提交"
                    ),
                ),
                (
                    "run_count",
                    models.PositiveIntegerField(default=0, verbose_name="运行次数"),
                ),
                (
                    "submission_count",
                    models.PositiveIntegerField(default=0, verbose_name="提交次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="python_judge.judgeproblem",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户 Python 题目状态",
                "verbose_name_plural": "用户 Python 题目状态",
                "db_table": "python_judge_pythonjudgeprogress",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="python_judg_user_id_cdb237_idx"
                    ),
                    models.Index(
                        fields=["user", "marked"], name="python_judg_user_id_20ba3d_idx"
                    ),
                ],
                "unique_together": {("user", "problem")},
            },
        ),
    ]
