# Generated by Django 6.0.6 on 2026-06-17 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="邮箱"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("register", "注册")],
                        default="register",
                        max_length=20,
                        verbose_name="用途",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(max_length=128, verbose_name="验证码哈希"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="验证次数"
                    ),
                ),
                (
                    "request_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="请求 IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "邮箱验证码",
                "verbose_name_plural": "邮箱验证码",
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "created_at"],
                        name="accounts_em_email_60ecc0_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_em_expires_0ae87f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=40, verbose_name="昵称"),
                ),
                (
                    "bio",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="个人简介"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="accounts/avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codemark_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
    ]
