# Generated by Django 6.0.6 on 2026-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_default_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="default_avatar",
            field=models.CharField(
                choices=[
                    ("images/default-avatars/avatar-01.png", "默认头像 01"),
                    ("images/default-avatars/avatar-02.png", "默认头像 02"),
                    ("images/default-avatars/avatar-03.png", "默认头像 03"),
                    ("images/default-avatars/avatar-04.png", "默认头像 04"),
                    ("images/default-avatars/avatar-05.png", "默认头像 05"),
                    ("images/default-avatars/avatar-06.png", "默认头像 06"),
                    ("images/default-avatars/avatar-07.png", "默认头像 07"),
                    ("images/default-avatars/avatar-08.png", "默认头像 08"),
                    ("images/default-avatars/avatar-09.png", "默认头像 09"),
                    ("images/default-avatars/avatar-10.png", "默认头像 10"),
                    ("images/default-avatars/avatar-11.png", "默认头像 11"),
                    ("images/default-avatars/avatar-12.png", "默认头像 12"),
                    ("images/default-avatars/generated-avatar-01.png", "默认头像 13"),
                    ("images/default-avatars/generated-avatar-02.png", "默认头像 14"),
                    ("images/default-avatars/generated-avatar-03.png", "默认头像 15"),
                    ("images/default-avatars/generated-avatar-04.png", "默认头像 16"),
                    ("images/default-avatars/generated-avatar-05.png", "默认头像 17"),
                    ("images/default-avatars/generated-avatar-06.png", "默认头像 18"),
                    ("images/default-avatars/generated-avatar-07.png", "默认头像 19"),
                    ("images/default-avatars/generated-avatar-08.png", "默认头像 20"),
                    ("images/default-avatars/generated-avatar-09.png", "默认头像 21"),
                    ("images/default-avatars/generated-avatar-10.png", "默认头像 22"),
                    ("images/default-avatars/generated-avatar-11.png", "默认头像 23"),
                    ("images/default-avatars/generated-avatar-12.png", "默认头像 24"),
                ],
                default="images/default-avatars/generated-avatar-01.png",
                max_length=128,
                verbose_name="默认头像",
            ),
        ),
    ]
