# Generated by Django 6.0.6 on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_selected_default_avatars"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="original_avatar",
            field=models.ImageField(
                blank=True,
                upload_to="accounts/original_avatars/",
                verbose_name="原始头像",
            ),
        ),
    ]
