# Generated by Django 5.2.15 on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_original_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarGalleryAdminEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "头像画册",
                "verbose_name_plural": "头像画册",
                "managed": False,
            },
        ),
    ]
