# Generated by Django 6.0.6 on 2026-06-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_avatargalleryadminentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_vip",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="VIP 用户"
            ),
        ),
    ]
