# Generated by Django 6.0.6 on 2026-06-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_userprofile_is_vip"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_permanent_vip",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="永久 VIP"
            ),
        ),
    ]
