# Generated by Django 6.0.6 on 2026-06-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_userprofile_is_permanent_vip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "注册"),
                    ("email_change_old", "邮箱变更-原邮箱"),
                    ("email_change_new", "邮箱变更-新邮箱"),
                ],
                default="register",
                max_length=20,
                verbose_name="用途",
            ),
        ),
    ]
