# Generated by Django 6.0.6 on 2026-06-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_emailverificationcode_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountLoginSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_email_password",
                    models.BooleanField(default=True, verbose_name="邮箱 + 密码"),
                ),
                (
                    "enable_email_code",
                    models.BooleanField(default=True, verbose_name="邮箱 + 邮箱验证码"),
                ),
                (
                    "enable_username_password",
                    models.BooleanField(default=True, verbose_name="用户名 + 密码"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "登录方式设置",
                "verbose_name_plural": "登录方式设置",
            },
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "注册"),
                    ("login", "邮箱验证码登录"),
                    ("email_change_old", "邮箱变更-原邮箱"),
                    ("email_change_new", "邮箱变更-新邮箱"),
                ],
                default="register",
                max_length=20,
                verbose_name="用途",
            ),
        ),
    ]
