# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_accountloginsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="share_storage_quota_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="留空表示长期有效；到期后恢复默认空间规则。",
                null=True,
                verbose_name="分享空间有效期",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="share_storage_quota_mb",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="留空使用默认规则：非会员 100 MB，VIP/管理员不限额。",
                null=True,
                verbose_name="分享空间上限（MB）",
            ),
        ),
    ]
