# Generated by Django 6.0.6 on 2026-06-18 23:41

import apps.blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=32, unique=True, verbose_name="标签名"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=64,
                        unique=True,
                        verbose_name="URL 标识",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "博客标签",
                "verbose_name_plural": "博客标签",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=160,
                        unique=True,
                        verbose_name="URL 标识",
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, max_length=360, verbose_name="摘要"),
                ),
                ("content", models.TextField(verbose_name="正文")),
                (
                    "content_format",
                    models.CharField(
                        choices=[("markdown", "Markdown"), ("richtext", "富文本")],
                        default="markdown",
                        max_length=16,
                        verbose_name="编辑器类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=40, verbose_name="分类"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.blog.models.blog_cover_upload_path,
                        verbose_name="封面图",
                    ),
                ),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="允许评论"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="blog.blogtag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客文章",
                "verbose_name_plural": "博客文章",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.blog.models.blog_image_upload_path,
                        verbose_name="图片",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="原始文件名"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="MIME 类型"
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="文件大小"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="宽度"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="高度"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="blog.blogpost",
                        verbose_name="关联文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客图片",
                "verbose_name_plural": "博客图片",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1200, verbose_name="评论内容")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="已删除"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogpost",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客评论",
                "verbose_name_plural": "博客评论",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "is_deleted", "created_at"],
                        name="blog_blogco_post_id_0ffd8b_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BlogBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="blog.blogpost",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客收藏",
                "verbose_name_plural": "博客收藏",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "user"), name="unique_blog_bookmark"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BlogReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="blog.blogpost",
                        verbose_name="文章",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客点赞",
                "verbose_name_plural": "博客点赞",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "user"), name="unique_blog_reaction"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["status", "-published_at"], name="blog_blogpo_status_c0e87f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["author", "status", "-updated_at"],
                name="blog_blogpo_author__ad5b4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["category", "status"], name="blog_blogpo_categor_a21b24_idx"
            ),
        ),
    ]
