# Generated by Django 6.0.6 on 2026-06-18 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcomment",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="已置顶"),
        ),
        migrations.AddField(
            model_name="blogcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="blog.blogcomment",
                verbose_name="父评论",
            ),
        ),
        migrations.AddField(
            model_name="blogcomment",
            name="pinned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="置顶时间"),
        ),
        migrations.AddIndex(
            model_name="blogcomment",
            index=models.Index(
                fields=["post", "parent", "is_deleted", "created_at"],
                name="blog_blogco_post_id_63985b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blogcomment",
            index=models.Index(
                fields=["post", "is_pinned", "-pinned_at"],
                name="blog_blogco_post_id_9d48ff_idx",
            ),
        ),
    ]
