# Generated by Django 6.0.6 on 2026-06-19 01:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogcomment_is_pinned_blogcomment_parent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogArticleApiAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "window_start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="计数周期开始"
                    ),
                ),
                (
                    "request_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="周期内请求次数"
                    ),
                ),
                (
                    "last_requested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后请求时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_accesses",
                        to="blog.blogpost",
                        verbose_name="文章",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_article_api_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章 API 请求次数",
                "verbose_name_plural": "文章 API 请求次数",
                "indexes": [
                    models.Index(
                        fields=["user", "post"], name="blog_blogar_user_id_123e3b_idx"
                    ),
                    models.Index(
                        fields=["window_start"], name="blog_blogar_window__444e56_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "post"), name="unique_blog_article_api_access"
                    )
                ],
            },
        ),
    ]
