# Generated by Django 6.0.6 on 2026-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogarticleapiaccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="api_request_count",
            field=models.PositiveIntegerField(default=0, verbose_name="API 请求总次数"),
        ),
    ]
