# Generated by Codex on 2026-06-21

from django.db import migrations, models
from django.utils import timezone


MEMBERSHIP_CONTENT = """
## 当前会员

当前账号：{{ display_name }}。VIP 页面仅对 VIP、永久 VIP 和管理员开放，用于集中查看会员权益、文章 API 教程和使用规范。

## 会员权益

- 可访问文章 API，读取已发布文章的完整结构化数据。
- 可复制浏览器登录态 Cookie，用于自己的脚本、分析工具或请求工具。
- 可查看请求额度、接口返回字段和常见状态码说明。
- 永久 VIP 与普通 VIP 当前拥有相同的文章 API 访问能力，后续权益可在后台继续扩展。

## 适用场景

VIP 文章 API 适合自动化归档、AI 分析、个人知识库同步、数据看板和离线检索。请求内容包含文章正文、作者、标签、统计信息和评论结构，便于后续处理。

## 使用提醒

Cookie 相当于登录凭证，只应保存在自己的本地环境或服务器密钥管理中。不要把 Cookie 写入公开仓库、公开网页、截图或分享消息。
""".strip()


API_CONTENT = """
## 账号权限

VIP 账号可以读取文章完整 JSON 数据。每个 VIP 账号对每篇文章在 {{ api_window_days }} 天内最多请求 {{ api_limit }} 次，管理员不受次数限制。

## 接口地址

每篇文章的 API 地址格式如下：

```http
GET /blog/<文章 slug>/api/
```

当前示例文章：{{ sample_post_title }}

当前可用示例：

```plaintext
{{ sample_api_url }}
```

## 请求示例

浏览器或前端请求：

```javascript
fetch("{{ sample_api_url }}", {
  method: "GET",
  credentials: "include",
  headers: {
    "Accept": "application/json"
  }
})
  .then((response) => response.json())
  .then((data) => console.log(data.article.title));
```

Python 分析脚本：

```python
import requests

url = "{{ sample_api_url }}"
cookies = {{ current_cookie_python }}

response = requests.get(url, cookies=cookies, headers={"Accept": "application/json"})
response.raise_for_status()

payload = response.json()
article = payload["article"]

print(article["title"])
print(article["content"])
print(article["stats"])
```

## 获取 Cookies

文章 API 使用当前登录会话识别 VIP 权限。浏览器中点击文章页的 API 数据按钮只会复制链接；如果要在脚本、Postman 或 curl 中请求，需要携带同一账号的 Cookie。

当前 Cookie 请求头：

```http
Cookie: {{ current_cookie_header }}
```

备用方法：

1. 登录 VIP 账号后打开浏览器开发者工具。
2. 进入 Application 或应用面板。
3. 在 Cookies 中选择当前站点域名。
4. 复制 sessionid 的值，并按 `Cookie: sessionid=你的-sessionid-值` 放入请求头。

也可以在 Network 面板选中一次 API 请求，右键选择 Copy as cURL。复制出的命令会自动带上 Cookie。

## 返回数据

成功返回时，JSON 中会包含这些核心字段：

- `usage`：当前请求窗口、次数上限、已用次数、剩余次数、重置时间。
- `article.title`：文章标题。
- `article.author`：作者账号、展示名和主页链接。
- `article.content`：原始正文，保留 Markdown 或富文本内容。
- `article.content_html`：服务端渲染并清洗后的 HTML。
- `article.stats`：阅读量、API 请求总次数、点赞、收藏、评论、字数和阅读时长。
- `article.comments`：评论和回复列表，包含作者、内容、置顶状态和时间。

## 状态码

- `200`：请求成功。
- `401`：未登录。
- `403`：账号不是 VIP 或管理员。
- `404`：文章不存在，或当前账号不可见。
- `429`：{{ api_window_days }} 天内 {{ api_limit }} 次请求额度已用完。
""".strip()


RULES_CONTENT = """
## 内容使用边界

VIP API 面向个人学习、分析、归档和自动化处理。请控制请求频率，不要批量抓取无关内容，不要绕过页面权限，也不要把接口结果公开转售或二次分发。

## 安全建议

- Cookie 只保存在可信设备、脚本环境或服务器密钥管理中。
- 定期清理不再使用的脚本配置和请求工具历史记录。
- 如果怀疑 Cookie 泄露，请退出登录并重新登录刷新会话。
- 公开演示或截图时，遮挡 `sessionid` 等凭证。

## 配额说明

当前文章 API 配额为每篇文章 {{ api_window_days }} 天 {{ api_limit }} 次。额度按账号和文章分别计算，请把自动任务设计成增量同步，避免重复拉取同一篇文章。

## 更新说明

VIP 说明、API 教程和使用规范都会在此中心持续更新。页面内容以后台发布版本为准。
""".strip()


def seed_vip_pages(apps, schema_editor):
    BlogVipPage = apps.get_model("blog", "BlogVipPage")
    now = timezone.now()
    pages = [
        {
            "slug": "membership",
            "title": "会员说明",
            "summary": "了解当前 VIP 权益、适用场景和账号安全提醒。",
            "content": MEMBERSHIP_CONTENT,
            "is_home": True,
            "sort_order": 10,
        },
        {
            "slug": "api",
            "title": "API 教程",
            "summary": "查看文章 API 地址、请求示例、Cookie 获取方式和返回字段。",
            "content": API_CONTENT,
            "is_home": False,
            "sort_order": 20,
        },
        {
            "slug": "rules",
            "title": "使用规范",
            "summary": "查看 API 使用边界、Cookie 安全建议和配额说明。",
            "content": RULES_CONTENT,
            "is_home": False,
            "sort_order": 30,
        },
    ]
    for page in pages:
        BlogVipPage.objects.update_or_create(
            slug=page["slug"],
            defaults={
                "title": page["title"],
                "summary": page["summary"],
                "content": page["content"],
                "content_format": "markdown",
                "status": "published",
                "is_home": page["is_home"],
                "show_in_nav": True,
                "sort_order": page["sort_order"],
                "published_at": now,
            },
        )


def move_legacy_vip_page_table(apps, schema_editor):
    table_name = "blog_blogvippage"
    existing_tables = set(schema_editor.connection.introspection.table_names())
    if table_name not in existing_tables:
        return

    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }
    required_columns = {
        "slug",
        "summary",
        "content",
        "content_format",
        "is_home",
        "show_in_nav",
        "sort_order",
    }
    if required_columns.issubset(columns):
        return

    with schema_editor.connection.cursor() as cursor:
        constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)
    for index_name, details in constraints.items():
        if not details.get("index") or details.get("primary_key") or index_name.startswith("sqlite_autoindex"):
            continue
        quoted_index = schema_editor.quote_name(index_name)
        quoted_table = schema_editor.quote_name(table_name)
        if schema_editor.connection.vendor == "mysql":
            schema_editor.execute(f"DROP INDEX {quoted_index} ON {quoted_table}")
        else:
            schema_editor.execute(f"DROP INDEX IF EXISTS {quoted_index}")

    base_legacy_name = "blog_blogvippage_legacy_0005"
    legacy_name = base_legacy_name
    suffix = 2
    while legacy_name in existing_tables:
        legacy_name = f"{base_legacy_name}_{suffix}"
        suffix += 1
    schema_editor.execute(
        schema_editor.sql_rename_table
        % {
            "old_table": schema_editor.quote_name(table_name),
            "new_table": schema_editor.quote_name(legacy_name),
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogpost_api_request_count"),
    ]

    operations = [
        migrations.RunPython(move_legacy_vip_page_table, migrations.RunPython.noop),
        migrations.CreateModel(
            name="BlogVipPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=80, verbose_name="页面标题")),
                ("slug", models.SlugField(allow_unicode=True, blank=True, max_length=80, unique=True, verbose_name="URL 标识")),
                ("summary", models.TextField(blank=True, max_length=240, verbose_name="页面摘要")),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "支持 Markdown 或富文本。Markdown 可使用占位符：{{ display_name }}、{{ sample_api_url }}、"
                            "{{ sample_post_title }}、{{ current_cookie_header }}、{{ current_cookie_python }}、"
                            "{{ api_window_days }}、{{ api_limit }}。"
                        ),
                        verbose_name="页面正文",
                    ),
                ),
                (
                    "content_format",
                    models.CharField(
                        choices=[("markdown", "Markdown"), ("richtext", "富文本")],
                        default="markdown",
                        max_length=16,
                        verbose_name="编辑器类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("is_home", models.BooleanField(db_index=True, default=False, verbose_name="作为 VIP 首页")),
                ("show_in_nav", models.BooleanField(default=True, verbose_name="显示在 VIP 导航")),
                ("sort_order", models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name="排序")),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="发布时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "VIP 内容页",
                "verbose_name_plural": "VIP 内容页",
                "ordering": ["sort_order", "title"],
                "indexes": [
                    models.Index(fields=["status", "sort_order"], name="blog_vip_status_order_idx"),
                    models.Index(fields=["status", "is_home"], name="blog_vip_status_home_idx"),
                ],
            },
        ),
        migrations.RunPython(seed_vip_pages, migrations.RunPython.noop),
    ]
