# Generated by Django 6.0.6 on 2026-06-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSidebarAdminEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章侧边栏配置",
                "verbose_name_plural": "文章侧边栏配置",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleSidebarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        db_index=True, max_length=700, unique=True, verbose_name="路径"
                    ),
                ),
                (
                    "parent_path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=700,
                        verbose_name="父级路径",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[("file", "文章"), ("dir", "目录")],
                        max_length=12,
                        verbose_name="类型",
                    ),
                ),
                (
                    "title_override",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="自定义标题"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="排序"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "文章侧边栏条目",
                "verbose_name_plural": "文章侧边栏条目",
                "ordering": ("parent_path", "sort_order", "path"),
            },
        ),
    ]
