# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_sidebar_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesidebaritem",
            name="is_hidden",
            field=models.BooleanField(db_index=True, default=False, verbose_name="隐藏"),
        ),
    ]
