# Generated by Django 5.2.15 on 2026-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SharedFileAdminEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "分享文件",
                "verbose_name_plural": "分享文件后台",
                "managed": False,
            },
        ),
    ]
